/* Crate Quest levels - GENERATED FILE, do not edit by hand.
 * Regenerate with: node tools/generate_levels.js --seed 2026
 * Every level ships with a verified optimal-push solution (LURD notation:
 * lowercase = walk, uppercase = push). */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.CRATE_LEVELS = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return [
  {id:1,world:1,worldName:"First Steps",boxes:1,pushes:1,moves:1,
   rows:["#######","#     #","# .$@ #","###   #","--#   #","--#####"],
   solution:"L"},
  {id:2,world:1,worldName:"First Steps",boxes:1,pushes:2,moves:4,
   rows:["####--","#  ###","#    #","#@$  #","#  . #","######"],
   solution:"RurD"},
  {id:3,world:1,worldName:"First Steps",boxes:1,pushes:3,moves:5,
   rows:["######","# @# #","# $# #","#   .#","#  # #","######"],
   solution:"DldRR"},
  {id:4,world:1,worldName:"First Steps",boxes:1,pushes:4,moves:12,
   rows:["######","# .  #","#    #","#   ##","#  $#-","#  @#-","#####-"],
   solution:"UUluurrdLdlU"},
  {id:5,world:1,worldName:"First Steps",boxes:1,pushes:5,moves:7,
   rows:["#######","#    .#","#     #","#@$   #","#  #  #","#######"],
   solution:"RRRdrUU"},
  {id:6,world:1,worldName:"First Steps",boxes:1,pushes:5,moves:11,
   rows:["####---","# .#---","#  ####","#     #","#   $@#","#  ####","####---"],
   solution:"LLullddrUUU"},
  {id:7,world:1,worldName:"First Steps",boxes:1,pushes:5,moves:15,
   rows:["###-###","# ### #","#  ##.#","#     #","# $## #","# @   #","#######"],
   solution:"UluRRRllddrrruU"},
  {id:8,world:1,worldName:"First Steps",boxes:1,pushes:5,moves:15,
   rows:["---###-","--##@#-","### $##","#     #","#.    #","#######"],
   solution:"DlddrruLulDrdLL"},
  {id:9,world:1,worldName:"First Steps",boxes:1,pushes:6,moves:18,
   rows:["--#####","-##   #","##  $@#","#     #","## #  #","#.    #","#######"],
   solution:"LulDrdLulDDurrddlL"},
  {id:10,world:1,worldName:"First Steps",boxes:1,pushes:6,moves:10,
   rows:["--###--","###@###","# #$#.#","#   # #","#     #","#     #","#######"],
   solution:"DDldRRdrUU"},
  {id:11,world:2,worldName:"Two at a Time",boxes:2,pushes:6,moves:16,
   rows:["#####--","# . #--","#  $##-","#   .##","#  $@ #","#     #","#######"],
   solution:"LuluurDldRddlUUU"},
  {id:12,world:2,worldName:"Two at a Time",boxes:2,pushes:7,moves:18,
   rows:["######-","#    #-","#   $##","# ..  #","#  #$ #","####@ #","---####"],
   solution:"UruLLuurDDrddlUruL"},
  {id:13,world:2,worldName:"Two at a Time",boxes:2,pushes:8,moves:21,
   rows:["###----","# ##---","#  ####","#   $ #","#     #","# @$..#","###   #","--#####"],
   solution:"RRuruLLdlluurDldRRurD"},
  {id:14,world:2,worldName:"Two at a Time",boxes:2,pushes:9,moves:27,
   rows:["######-","#  $+#-","# $ ###","#   # #","#     #","#    .#","#######"],
   solution:"LddlluuRDldRurDDldRRuluuluR"},
  {id:15,world:2,worldName:"Two at a Time",boxes:2,pushes:10,moves:42,
   rows:["----####","-####  #","##   @ #","# ###$ #","#  $   #","#  ..  #","########"],
   solution:"DrddlllluRdrrruulDrdLLLuRdrruulDrdLulllldR"},
  {id:16,world:2,worldName:"Two at a Time",boxes:2,pushes:10,moves:17,
   rows:["########","#+$    #","# $#   #","#  ### #","#   ## #","# . ## #","##  ## #","-#######"],
   solution:"RDDDuuuRRdrruLLLL"},
  {id:17,world:2,worldName:"Two at a Time",boxes:2,pushes:11,moves:24,
   rows:["########","# @  . #","# $#####","## ### #","-#  ##.#","##  ##$#","#      #","########"],
   solution:"DDDrddrrrUdllllUUUUluRRR"},
  {id:18,world:2,worldName:"Two at a Time",boxes:2,pushes:11,moves:28,
   rows:["-####--","-#..###","-#    #","-#    #","###  ##","#@$ $ #","#     #","#######"],
   solution:"RdrrUdlUrUdlUrUruLLrddlUUdlU"},
  {id:19,world:2,worldName:"Two at a Time",boxes:2,pushes:12,moves:36,
   rows:["####---","#. #---","# $#---","#  ####","#   $@#","#    .#","#######"],
   solution:"LLdlluurDldRRRulluluurDDlddrruLdlUUU"},
  {id:20,world:2,worldName:"Two at a Time",boxes:2,pushes:12,moves:19,
   rows:["########","#   #  #","# +$   #","#  #   #","# $#####","#   #---","#. ##---","####----"],
   solution:"RRdrruLLLLulDDDDrUU"},
  {id:21,world:3,worldName:"Tight Corners",boxes:2,pushes:13,moves:31,
   rows:["----####","----#  #","--###$ #","###  $@#","#.     #","#      #","#  .   #","########"],
   solution:"LruulDDDrdLLulDuuRdrruulDrdLLLL"},
  {id:22,world:3,worldName:"Tight Corners",boxes:2,pushes:14,moves:32,
   rows:["########","#      #","#      #","# $$ #.#","# @## .#","###### #","-----###"],
   solution:"UluRRRRurDDulldLullddrUluRRRRurD"},
  {id:23,world:3,worldName:"Tight Corners",boxes:3,pushes:13,moves:49,
   rows:["---####-","---#  ##","####  .#","# $ $  #","#.@$ . #","########"],
   solution:"RRluRdllluRdrruurrddLLLLuRdrrruullDurrddlUlldRuuR"},
  {id:24,world:3,worldName:"Tight Corners",boxes:3,pushes:13,moves:22,
   rows:["########","# .    #","#  ##$ #","#.   $ #","###  #.#","--### $#","----# @#","----####"],
   solution:"UUULLLLuurrrrDDlUruLLL"},
  {id:25,world:3,worldName:"Tight Corners",boxes:3,pushes:13,moves:29,
   rows:["#####---","#   #---","#   #---","#. #####","#.$$   #","#+$    #","########"],
   solution:"RRRurrdLLLLUdrruLLUluurrdLulD"},
  {id:26,world:3,worldName:"Tight Corners",boxes:3,pushes:13,moves:40,
   rows:["--###---","### #---","#   ###-","# . #+##","#  $$$ #","#    . #","########"],
   solution:"DrdLLLUlldRurRdrUllldRRulluurDlddrruLdlU"},
  {id:27,world:3,worldName:"Tight Corners",boxes:3,pushes:14,moves:35,
   rows:["########","#      #","# $@$..#","# $### #","#  #-# #","# #### #","# ##  .#","########"],
   solution:"RRurDDDDuuuullllldRRRRllllddrUluRRR"},
  {id:28,world:3,worldName:"Tight Corners",boxes:3,pushes:15,moves:39,
   rows:["######--","#   .#--","#   ####","#  . $+#","# $ #  #","# $ ####","#    #--","######--"],
   solution:"LLLullddRlddrUluuRRRRllllddrrUdlUUUluRR"},
  {id:29,world:3,worldName:"Tight Corners",boxes:3,pushes:15,moves:47,
   rows:["########","#@     #","#$  .  #","# $. # #","#.$  # #","#  ### #","#  #-###","####----"],
   solution:"DDDRluRdddlUUUrurrddLruulldRllddrUruuullDDRdrrU"},
  {id:30,world:3,worldName:"Tight Corners",boxes:3,pushes:16,moves:50,
   rows:["--######","--#    #","--#   .#","#####  #","#   *@.#","#  $ $ #","#    # #","########"],
   solution:"LdLrurrdLulLddlluRluRRRRlllddrUluRRlddrUrUUruulldR"},
  {id:31,world:4,worldName:"Warehouse",boxes:3,pushes:16,moves:51,
   rows:["---####--","-### @##-","-# $ $ #-","-#    $#-","## #.  ##","# .     #","# .     #","#########"],
   solution:"DrDDlddrruLLLLruulldDrrurruLulDDrdLLruulluRdrruulDD"},
  {id:32,world:4,worldName:"Warehouse",boxes:3,pushes:17,moves:49,
   rows:["---#####","---#   #","---#  +#","---# $$#","-####  #","-# . $ #","##     #","#.     #","########"],
   solution:"DDlDlddrruLLLulDrdLuurrruruulDDDlddrruLLdlUrrrUUU"},
  {id:33,world:4,worldName:"Warehouse",boxes:3,pushes:17,moves:53,
   rows:["#########","#   .   #","#      +#","# .#  $$#","#  ##$  #","#####   #","----### #","------# #","------###"],
   solution:"DLddrUUlulldRurDrddllUUrrdLdlUruuLLLulDrrrrddlUruLdlU"},
  {id:34,world:4,worldName:"Warehouse",boxes:3,pushes:17,moves:83,
   rows:["#####----","#   ###--","# #$# #--","# # # ##-","#  $@$ #-","#    . ##","### .   #","--#  .  #","--#######"],
   solution:"LdlluuuurrDDDuuullddddrRurDldRurDuruLLdllluuuurrddDuuullddddrRurDllluRluuurrddDldRR"},
  {id:35,world:4,worldName:"Warehouse",boxes:3,pushes:18,moves:64,
   rows:["########","# .    #","##$### #","# $@$  #","#      #","###.   #","--## . #","---#####"],
   solution:"RdllluRdrrrruuullllDDldRRRuLddrrruuLDDuuruulllldDldRurDrruLLdlUU"},
  {id:36,world:4,worldName:"Warehouse",boxes:3,pushes:18,moves:50,
   rows:["########","#      #","#   #@ #","##   $##","##$$#  #","#.   ..#","########"],
   solution:"DDrdLLLLUdrrruullDldRRRllulUruulldRurDldRRluurrdDD"},
  {id:37,world:4,worldName:"Warehouse",boxes:3,pushes:19,moves:73,
   rows:["########","#    . #","#     .#","#  .  ##","# $  ##-","#@$  #--","# $###--","#  #----","####----"],
   solution:"RUdlddrUUluuurrddrdLuuullddRlddrUluuRRllddrrUdlUUluRRRRlllddrrUdlluurRdrU"},
  {id:38,world:4,worldName:"Warehouse",boxes:3,pushes:19,moves:44,
   rows:["####-----","#  #-----","# $#-----","#  ######","#   $@$ #","#  .    #","#       #","#.  .  ##","########-"],
   solution:"LLdlluurDldRRurDDurrruLLLLLulDDDuuuuurDDDldR"},
  {id:39,world:4,worldName:"Warehouse",boxes:3,pushes:19,moves:78,
   rows:["#########","#  . .  #","# #  $ ##","#  #  ###","#@* $ # #","####    #","---######"],
   solution:"RuluurrrrrdLdddlUruuulllldddrRRdrUUUruLLLdRDrddlUruUddllluluuRldddrrrruulDrdLL"},
  {id:40,world:4,worldName:"Warehouse",boxes:3,pushes:21,moves:67,
   rows:["#########","#     . #","#     . #","#  $  $ #","#  ####.#","####--#$#","------#@#","------###"],
   solution:"UUULuurDDullldLurrrdLLulllddrUluurrdrdLuulldRRRRllllddrUluRRRdrUluR"},
  {id:41,world:5,worldName:"Logistics",boxes:3,pushes:22,moves:49,
   rows:["-----####","-----#  #","-----#$ #","-----#  #","######$ #","#.    $@#","#.      #","#.      #","#########"],
   solution:"LruulDDrdLLLLLulDrrrrruuuruulDDDDrdLLLLLrrrruLLLL"},
  {id:42,world:5,worldName:"Logistics",boxes:4,pushes:21,moves:55,
   rows:["######-","#..  #-","#+   #-","#$. ###","# $$  #","# $   #","#  ####","#    #-","######-"],
   solution:"DDDRRlddlUUrrUdllUUUdddrrurrdLLLdlUrUdlUrrUdllUdrruUruL"},
  {id:43,world:5,worldName:"Logistics",boxes:4,pushes:22,moves:76,
   rows:["#########","# $    .#","#       #","#   . .$#","#   $ $+#","#  ### ##","####-###-"],
   solution:"UlldLurrrdLuuurDDllldLurrrdLLulllddrUluurrdrdLuulldRRRRllllddrUluRRulluRRRRR"},
  {id:44,world:5,worldName:"Logistics",boxes:4,pushes:23,moves:82,
   rows:["#######--","#   . #--","#     #--","# .  $#--","###  .###","-## $$  #","-#@$.   #","-########"],
   solution:"RRRlluurrUdllddrrUdlUrrrdLLulluurrDullddrRlUdrdrruLLullddRUrrdLulluuuurrDDLLddrUUU"},
  {id:45,world:5,worldName:"Logistics",boxes:4,pushes:23,moves:69,
   rows:["####-----","#@ #-----","#$$#-###-","#. ### ##","# $##   #","# *     #","#    .  #","#  #.   #","#########"],
   solution:"DDDDRRRdrruulDrdLulDullluurDldRRRdrruulDllluuluurDDlddrddlUUUUrDuuulD"},
  {id:46,world:5,worldName:"Logistics",boxes:4,pushes:23,moves:55,
   rows:["--#######","--#     #","--# $ $ #","--###   #","----##* #","######. #","#.     $#","#  #  #+#","#########"],
   solution:"UUUUlluurrDDDDDuuulDDrdLLLLLrrrruuuluurDDDuuullldRRurDD"},
  {id:47,world:5,worldName:"Logistics",boxes:4,pushes:23,moves:52,
   rows:["######--","# .$ #--","# $$ ##-","#   $@#-","#   ###-","#   ####","#    . #","#   ..##","#######-"],
   solution:"LLruuLDDDDDldRRuluulluuRDldRurDDDldRuuuuruulDDDDldRR"},
  {id:48,world:5,worldName:"Logistics",boxes:4,pushes:24,moves:64,
   rows:["#####----","#@  #----","#$*##----","#  #-----","#.*######","# $     #","#       #","# .######","####-----"],
   solution:"DDDDRRRllluurDldRddlUruuuluurDDDDDrruLdrrruLLdllUUUdddrruLdlUdlU"},
  {id:49,world:5,worldName:"Logistics",boxes:4,pushes:24,moves:73,
   rows:["-###-----","-# ######","-#   +  #","-#  $$$ #","-#### ###","#####  #-","#. $ ..##","#       #","#########"],
   solution:"DDDrddlluLdrrruLuuuurrdLulDDDuuLrddrddlUdlluRRllLrrrUUUlulldRRuRDDDuurruL"},
  {id:50,world:5,worldName:"Logistics",boxes:4,pushes:24,moves:57,
   rows:["##########","#@$    . #","# $$$    #","##       #","-##  .  .#","--###   .#","----######"],
   solution:"RRDRlulldRdRRRRRurDDulllluRRRurDDlllllluRRdrruulDDulluRRR"},
  {id:51,world:6,worldName:"Cargo Bay",boxes:4,pushes:26,moves:72,
   rows:["---####--","---# @###","#####$. #","#   $ . #","#     $.#","# *######","#    #---","######---"],
   solution:"DrdrdLLLLulldRRRRRuulDrdLLLulldRlddrUluurrRRllllddrUluRRRdLulDrrrrUdlluR"},
  {id:52,world:6,worldName:"Cargo Bay",boxes:4,pushes:26,moves:78,
   rows:["--###----","--#@##---","###$ #---","#    ####","#.$$    #","#$     .#","#       #","###  #..#","--#######"],
   solution:"DrdddllURRuulDrddlluRurDldRRRurDDuulLdlluurDldRRurDDuullllluRRurDDldRRRdlllllU"},
  {id:53,world:6,worldName:"Cargo Bay",boxes:4,pushes:26,moves:94,
   rows:["-####----","-#  #----","-#. ###--","##.#  #--","#.    #--","#   $$###","#  #$   #","#@$.    #","#########"],
   solution:"RRRRllluuurrrDLulldddrrUUruLdddrUrrdLLLuuurDlddrruLulLLrrrddlUruulLrrddlUruLdllUUddrruLdldlUrU"},
  {id:54,world:6,worldName:"Cargo Bay",boxes:4,pushes:26,moves:102,
   rows:["------####","-###### .#","-#@$ $   #","##$#    .#","#  #$  . #","#  .     #","##########"],
   solution:"DDldRRRRuuluRdddlUrrrdLuuluRdrruulDDldlldlluuuRRRRddllUddlluuurRddrrdLLuurrrruulDldlluRRRldddrruuUlldR"},
  {id:55,world:6,worldName:"Cargo Bay",boxes:4,pushes:28,moves:143,
   rows:["-#######--","-#     ###","-#..  $  #","-#  ##$  #","-##$ @$  #","### .  ###","#    ###--","#.   #----","######----"],
   solution:"RdlllUUluurrdrRullllddrdrrrUrrdLLLdlluuluurrrrDullllddrddrruLrrruruLLullllddrDDDrdLLuruurrrruulDrdLLLrruuullllddrDDrddlluRdrUluuuluurrdLurrrdLL"},
  {id:56,world:6,worldName:"Cargo Bay",boxes:5,pushes:25,moves:79,
   rows:["--###-----","--# ##----","--#  ##---","--# . ##--","###$   #--","#.#    #--","#  $  $###","#.$.   $+#","##########"],
   solution:"LLUlullUdrddlUlldRurruulDrdLLdlUrrrdLLuruuruulDDDrddlluRurrdrdLuuurDDldRRllLUUU"},
  {id:57,world:6,worldName:"Cargo Bay",boxes:4,pushes:30,moves:94,
   rows:["#######---","#     #---","#    .#---","# $ # ####","# $#.    #","#. ## $###","#  #@$   #","###.     #","--########"],
   solution:"RuuuulldLDlddrUUUruulldRRRurDDDDDRdLLrrrruLdlluuuuullllDDuurrrrdddddrruLdlUUUrDlddrruLdlUUruLU"},
  {id:58,world:6,worldName:"Cargo Bay",boxes:4,pushes:31,moves:124,
   rows:["----######","----#   .#","######   #","#.       #","#        #","#   #..###","#  $#  #--","#$$ $@##--","#    ##---","######----"],
   solution:"LdllUUddrruLrruuullllddrUrurrdddldllUdlUrrrruuuulllldRRRRurDldddlllUUluRRRurDlldlddrUdllUrrUdllUrrUluRRRRRdlllldllUrrrrrrrUU"},
  {id:59,world:6,worldName:"Cargo Bay",boxes:4,pushes:33,moves:104,
   rows:["----######","----#    #","-##### $ #","## .##  ##","#@$  .. #-","#  $ $  #-","#  ######-","#   .#----","######----"],
   solution:"RRRdLulDDldRRluuurrRRdLrrUluuurrdLulDDDldLLullddrUluRRdrrurrdLLLLrrurrUluurrdLulDDrddlllluRlllddrUluRdrU"},
  {id:60,world:6,worldName:"Cargo Bay",boxes:4,pushes:33,moves:147,
   rows:["--########","--# .    #","--#$ .   #","### .#   #","# $ .    #","#@$ #  # #","# $ ######","#  ##-----","####------"],
   solution:"RlddrUluuRRRRdrUlllllddrrUdlluurRuruulDDDRuurrrddlUruulldlddRdrUlllllddrUluRRRuuurrrdLLrrddlUruulllldddrRdrUlluluurDurrrdLrddlUUruLLrdddllllddrUluR"},
  {id:61,world:7,worldName:"Freight Yard",boxes:5,pushes:29,moves:138,
   rows:["###########","# .   .   #","# # ..  $ #","# $ $   $##","######   #-","---### .##-","---#@$ ##--","---##  #---","----####---"],
   solution:"RdrUUUruulldRurDDuulllldRRuullllddRRRurrrddlUruulldldRuurrdLurrrdLulldLurrrdLddrUluulldLurrrdLurrrdLulldLurrrdLLrddlUlllUdrrrruulllLddrrrU"},
  {id:62,world:7,worldName:"Freight Yard",boxes:4,pushes:34,moves:92,
   rows:["-###-####","-# #-# .#","## #-##.#","#. #--#.#","#$ #### #","# $ $ # #","#   $@  #","#   ##  #","#########"],
   solution:"LLdlluRRRRRllllluUrDrdrrrdrUUUUUddddllllulldRRRRRluLLdlluurDldRRurrdrdrUUUUdddllulldRRRdrUUU"},
  {id:63,world:7,worldName:"Freight Yard",boxes:5,pushes:30,moves:89,
   rows:["----######","----# .  #","----#$   #","#####   .#","#   $$   #","#    $@  #","#####  . #","---#.   $#","---### . #","-----#####"],
   solution:"LruulDDuLLdRRRurDDlddrrUdlluurDuullDrdLuulllluRRRRRurDDlddrrUUluuuullDDrddlluRdrrrUdllUUU"},
  {id:64,world:7,worldName:"Freight Yard",boxes:5,pushes:30,moves:90,
   rows:["#########-","#  .## .#-","#   ##. ##","#.$      #","# $      #","# $ ###  #","# $##-####","#* ####---","#@    #---","#######---"],
   solution:"UUUUURRddLDuruulldRurRRRlllldddlddrUUUUlDDuuuRRRRlllddrUluuulDrddrrrrrUdlUdlllUrrrrUdllllU"},
  {id:65,world:7,worldName:"Freight Yard",boxes:5,pushes:31,moves:78,
   rows:["###########","#   $   . #","# $  # $. #","#@$  #  $ #","# #  #. ###","#    ####--","#   .#-----","#  . #-----","##  ##-----","-####------"],
   solution:"RluurrdDDDDuuulluRurDldRurDDDuuuluRRRRDrruLLdlddrUluRurrddLLulDuruLLLdlluRRRRR"},
  {id:66,world:7,worldName:"Freight Yard",boxes:5,pushes:32,moves:89,
   rows:["--#####----","--#  .#----","--#   ##---","--#    #---","### #  #---","#. $   #---","#$ $$  ####","#    .. $+#","#  ###### #","####----###"],
   solution:"LLLLLULUllDRdRRRRRRlllllluRRRurDllluRdrruulDDldlldlUruurrruullDurrdddllluRRddlllUrrrrUUUU"},
  {id:67,world:7,worldName:"Freight Yard",boxes:6,pushes:28,moves:96,
   rows:["-#######----","-# .   #####","-#$ .      #","-#  ## .$$ #","##  #####.##","#        $@#","##.*  $ #  #","-#  ########","-# ##-------","-#  #-------","-####-------"],
   solution:"LLLdLLulluuuulDDrddlddrUUrrdLulUUluRdddlddrUUUUlDDrdrrrruLLLdlUluurDDuuluurrrdrrrrDLullullllddrU"},
  {id:68,world:7,worldName:"Freight Yard",boxes:5,pushes:34,moves:88,
   rows:["---#######","---#     #","---# $ #.#","#####  # #","# $ $  $$#","#      #@#","#    . ###","#.  ####--","#.  .#----","######----"],
   solution:"ULLulDDrdLLulDDldRuuuuRdrruulDrdLLulDrdLLulDDuuuRRRdrruulDrdLLLLulDDuurrrruruulDDDDurrrU"},
  {id:69,world:7,worldName:"Freight Yard",boxes:5,pushes:34,moves:95,
   rows:["--########","--#.   $ #","--# $   .#","--#   ## #","--#.$#####","###  #----","# $$######","#. @  ## #","# .      #","##########"],
   solution:"UUUUrruullDDDDDDrdLuuuuurruLdlddddlluRdrUUrUUlDDDldRdrruLLLuruuurruullDDrrurrruLdllulldRRRRuLLL"},
  {id:70,world:7,worldName:"Freight Yard",boxes:5,pushes:34,moves:128,
   rows:["#########","# .   .@#","#  .   $#","#. #  $ #","#### $$ #","---##   #","----# $ #","----## .#","-----#  #","-----####"],
   solution:"DDDuulldDuurrddLdDuuUdddrddlUUUUrDDuuuuullddldRuuurrdddddllUrruuLLrrddlUdlUrruuLLLLLulDrrrrrrddllUdrruulLddrUluLrddlUrrUdllUruLL"},
  {id:71,world:8,worldName:"Dockside",boxes:6,pushes:30,moves:93,
   rows:["######----","# $. ##---","# $  .#---","# ##$ #---","#.## $#---","# ## @#---","#    $####","#      $ #","#.  .    #","#   #   ##","#  ##  . #","##########"],
   solution:"DDldRurDldRurDulululllluuuuRRRDrDDDlddrruLulDrdrrruLLLLLLulDuuuuurrrdDDrdLLLdlUUdrrruuuullluR"},
  {id:72,world:8,worldName:"Dockside",boxes:5,pushes:35,moves:98,
   rows:["---#######","---#.    #","---## $. #","#####$ ###","#  $@$$#--","#   .  #--","#  #####--","#.   #----","# .  #----","######----"],
   solution:"LdrrrULUURuLddddlluRdllluRRdrrruUlDrdLLLulDDDuuurRdrruulDrdLLLLulDDuurrrruuurDurrdLLulDDDrdLurUluR"},
  {id:73,world:8,worldName:"Dockside",boxes:5,pushes:36,moves:83,
   rows:["##########","#   .$   #","## $ $   #","-# $    ##","##$ #####-","# @ #-----","# ..#-----","#   #####-","#   . . #-","#########-"],
   solution:"UURRuulDDDDDDldRRRlluuuuuuurRRddLLulDDDDDldRuuuuurrruLLulDDDDuuuulDDDDuuurrrrrruLLL"},
  {id:74,world:8,worldName:"Dockside",boxes:4,pushes:40,moves:152,
   rows:["#########-","#     #@#-","#.#  $#$#-","# #   $ ##","# ###    #","#     $  #","#      ###","#.. ####--","#   .#----","######----"],
   solution:"DDDlluluurDDDrruLdlUluullldddddrrrrrUdllullluuuurrddrrdDrdLLulDDldRuuurruurrdrdLLruulldDrdLLLulDurrrrruLulDrdLLLLrrruuluullldddDDuuuuurrrrDDDrdLLLLdlUUU"},
  {id:75,world:8,worldName:"Dockside",boxes:4,pushes:41,moves:140,
   rows:["###-------","# ##------","#  #######","#. $@$   #","# $#    .#","#$       #","#    ..  #","##########"],
   solution:"RRddllllUluurDDuRRdddlllURRRRurDullulllDurrrdrruLLLrddlluluurDDurrdddlllURRRurDuullllDurrrdrrrruLLLLLrddlluluurDDurrdddlllURRRRRRdrUlllllllU"},
  {id:76,world:8,worldName:"Dockside",boxes:5,pushes:37,moves:157,
   rows:["#####---","#   #---","#   ####","#  $$. #","#   .$.#","# $ ## #","###$ #.#","#  @  .#","########"],
   solution:"UdrrruuuLLLURdrrdddllulUddrrruuullulllddRUUrrdLrrrdddllulUlURRldddrrruuuuLrddddlluluurRurDDDuullllluuurrDDuulldddrRRRurDDullllluRluurrdDldRRRllulluRurDDldRuR"},
  {id:77,world:8,worldName:"Dockside",boxes:5,pushes:37,moves:105,
   rows:["-#########-","-#       #-","## $     ##","#@$ $$    #","##  #.  ###","-####$  # #","----# .   #","----## . .#","-----# .  #","-----######"],
   solution:"RuRRRRddlUruulldllddrURRluurrdDldRurDDDDuuuuluurDDDDDldRRuluuullluRRurDDDDDuuullllluRRRurDDDrddllUdrruulD"},
  {id:78,world:8,worldName:"Dockside",boxes:5,pushes:38,moves:105,
   rows:["--########","--#@#.#  #","--#$    .#","--# $    #","### $    #","#   $ #  #","##. $##  #","-#   ##..#","-#########"],
   solution:"DDDRRRRurDDDuulllllDlddrUUUrrdLulDlddrrUUluRRRurDDDuuuullllDDrdddlluuRlddrruLrUluRluRRRRlllddrUrrrUdlllUU"},
  {id:79,world:8,worldName:"Dockside",boxes:6,pushes:34,moves:97,
   rows:["--#######-","--#    .#-","###*$$  #-","#@$    ###","## $$    #","-#  #   .#","-### .   #","---#  .  #","---###. ##","-----####-"],
   solution:"RRRllddrURRRuuullDRDDDrddlluRurDDuurruLdlluurDDDuullUdlluRRdrruUlDDDuuuulDrddlluRRurDDldRRuluuluR"},
  {id:80,world:8,worldName:"Dockside",boxes:6,pushes:34,moves:140,
   rows:["----######","----#.   #","----#    #","----## . #","#######  #","#  *  #  #","#.  $ # ##","# $$ .$ ##","##    .$@#","-#########"],
   solution:"LuLLdllUdrrurrdLulLdllURRRRluulLDurrddldlluRuurrddrdrUUUUUddddlluullddRRRdrUllldRulluRdrrrUUruulUdrddlUruuuLLdrrdddlddllluurDldllluuRlddrruL"},
  {id:81,world:9,worldName:"Deep Storage",boxes:6,pushes:35,moves:131,
   rows:["-###-------","-#@#-------","-#$###-----","##   ######","#  *$ . $ #","# * #     #","# $    ## #","#  # .  #.#","#        .#","###########"],
   solution:"DDrDRRddddllluluRRRRurDDldRRRluluulullDurrddddllluuRRRurruLdrrruLdlllddrUluRRRurDDullluLLulDDurrddddllluuRRdrruulDurrruLdldllllluuR"},
  {id:82,world:9,worldName:"Deep Storage",boxes:6,pushes:35,moves:112,
   rows:["##########","#        #","####.$$$ #","--## $@$ #","--# $ #  #","--#      #","--# . .  #","--#      #","--#  .#  #","--#   #  #","--# . .  #","--########"],
   solution:"LddlluRdrrruruuulllldDuurrDLurrrdLDDDDDDDrdLuuuuuuuuullddlDDDDDDuuuuuurDDDDuurruuLruulldDDDldRuuuuulDDDDuurrruLL"},
  {id:83,world:9,worldName:"Deep Storage",boxes:6,pushes:35,moves:85,
   rows:["#####-------","#   #-------","#   #-------","# $ #-------","#$  #---###-","#. $##--# #-","## $ #--# ##","##*  ##-#  #","# @ . #-#  #","#    .###*##","#   .     #-","###########-"],
   solution:"UUUlUURDDDDrddlluRRurDDuuuLdlUUluurDrDDldRurDDldRuuuluuluurDDDDldRurDuluulDDuuuuulDDD"},
  {id:84,world:9,worldName:"Deep Storage",boxes:5,pushes:40,moves:131,
   rows:["####--#####","#  ####.  #","#     .$@.#","#  $$ $ $ #","#   ##### #","#     #-###","# .   #----","# .  ##----","#   ##-----","#####------"],
   solution:"LLLLLDDlddrruLulDDuuuluurDDDDuuurrrdLurrrdLurrrdLulldLulllddrUluRRRdLurRRlllllddrUluRRdrrururrddlLLLLrrurRdlllluRRllllddrUluRRRdrrU"},
  {id:85,world:9,worldName:"Deep Storage",boxes:6,pushes:36,moves:74,
   rows:["############","#       $@.#","# $ $$$*.  #","#   # #    #","# ##       #","#  # .     #","#  ####..# #","####--#    #","------#### #","---------###"],
   solution:"LLDDrddlluRurDDuuuulLLDRurDDDDuuullDDuuuLLdRRRRlllldlluRRRRRllllluRRRRRRRR"},
  {id:86,world:9,worldName:"Deep Storage",boxes:5,pushes:41,moves:111,
   rows:["#######----","# .   #----","#   ###----","##  #------","## .#------","#. ####----","#     #####","#  $$$$   #","#+$     . #","###########"],
   solution:"RRRRRRurrdLLLLLLLuurrrDulllddrrRRRlllUruLddrrruLdlluuLrddlluUrrdLdrrruLLdlUruLLUUUruulldRurDDldddrddlUUdlUrUUUU"},
  {id:87,world:9,worldName:"Deep Storage",boxes:5,pushes:41,moves:178,
   rows:["--########","--# .  . #","--# #.   #","-##      #","## $$ # .#","#   $#####","#    $+#--","#  $ ###--","#   ##----","#####-----"],
   solution:"LLLulldRRRRlluUUrrdLDldlddrUluuuRdrUruuullDDuurrdddldllddrUluuRuRRlldlddrUrUdlluRuuurrddRuulllddRRllddrUdlddrUluurruurrrddlUruulldldRRluurrdDllldllddrUluuRlddrUrUUddlluRdrUrrUluL"},
  {id:88,world:9,worldName:"Deep Storage",boxes:5,pushes:41,moves:158,
   rows:["-----#####-","-----# ..#-","-###-#   #-","## ### .###","#  ##     #","#  ##$    #","#.$ #  ####","#  $ $ ####","#  .    $@#","###########"],
   solution:"LLLLLrruuuulDrdddlluRdrUUUlDrddlluLLdRurRlllUluurDDrdrrdrUllldllUdrrurrrUdllldlluRRRRdLuruuuRlddrUdlddrUluurrUUddllddrUluuRurUdldlddrUrUUddlluRuuuRlddrUdlddrU"},
  {id:89,world:9,worldName:"Deep Storage",boxes:6,pushes:38,moves:149,
   rows:["###########","#   ..  . #","#   $ $.  #","#  #### # #","#.  #-# $ #","#####-# $ #","------##  #","-#######$*#","-#       @#","-##########"],
   solution:"UUUULrddlUlUUUrrDDLdlUrruuulLLLdRRurrdddllUUddrruuulLddddrdrddlUUUluuuurrdddDDuuuuLulLrrdrdddlluuUrrddLruullllLLLulDDurrrrrrrrdddllUrruullluRdrrddllU"},
  {id:90,world:9,worldName:"Deep Storage",boxes:5,pushes:42,moves:129,
   rows:["------#####","------#   #","----###$$ #","----#   # #","----#     #","-######  ##","##   # .###","# .  #$$ .#","#    @$   #","#.   . ## #","###########"],
   solution:"RRUrrdLLLLdlluurDldRurrruUlDrdLLLLLulDrrrrruurUruLulldRurDDDlddrruLulDrdLLLLrrruuruurruuullDDDDDldRRdlllldllUrrrruuruurruuLulDDDD"},
  {id:91,world:10,worldName:"Grandmaster",boxes:6,pushes:39,moves:184,
   rows:["------###","#######.#","#     ..#","#  ###  #","#       #","##    # #","# $#$$..#","# @# $  #","# $*  ###","##      #","-########"],
   solution:"UUrrDDRddlllUluurururrrrdddLuruulldllldlddrdrrUdlluluururrdRRlullldlddrdrrurUddllluluururrdRdrrUUddlluulllUUluRRRRRdrUdldldddrruuUllddRdldlUUruulldRurDldRdddllluUUUUrrrrrUdlllllUluRRRR"},
  {id:92,world:10,worldName:"Grandmaster",boxes:6,pushes:39,moves:142,
   rows:["--###--------","--# ##-------","###. #-------","#@$  #-####--","##$ ####  ###","## $##.     #","# .$ #$  ## #","#   .#.#    #","##  ## #  $ #","-#.         #","-############"],
   solution:"RDDDDuuurUdldddrruLUddlluRurDldRddlUruuuluurDDDDDldRRRRRRuurrrddlLLLLLLLrrrrrrrruLLdlUrurruulllllDurrrrrdddlllUddlllllulUdrdrrrrruuUdrrruullLL"},
  {id:93,world:10,worldName:"Grandmaster",boxes:6,pushes:39,moves:153,
   rows:["###--------","# #######--","#.      #--","#.    $ #--","#   .@.##--","##   $##---","-#  $ #####","-#  # $   #","-#### $$# #","----#   ..#","----#    ##","----######-"],
   solution:"DDDRRDullDRddrruruuLLrrddldlluuluuLLrrddrddrruruullLddRRlluurDldRullUdrddlUruulUUddrddlUUUlldlUruuuurrrrdLdLLddrUluRluurrdLulDrdddlllUrUdrruulLLrddlUUruL"},
  {id:94,world:10,worldName:"Grandmaster",boxes:5,pushes:44,moves:197,
   rows:["##########","#    .   #","# # .   .#","#     .  #","# $ $ $  #","# $#######","#*  #-----","#@  #-----","#####-----"],
   solution:"UUUUrrrrdRullldRullldRlddrUluurruullDDDDrUluuurrddrdLurrrdLurrrdLulldLuuulllddRRllddrUluuurrdrrddlLrrurrdLLLruulldRRuullllddRRllddrUluuurrdrrddlLrruRRulllldRRuullllddRRRlllddrUluRRdrrrrrUdlllUdlUrU"},
  {id:95,world:10,worldName:"Grandmaster",boxes:6,pushes:40,moves:122,
   rows:["-------###","------##@#","------# $#","#######$ #","#  $   $ #","##     $.#","-##  #  *#","--#. #  .#","--# ##   #","--#   . .#","--########"],
   solution:"DDDLDDDuuuruulDDDDldddrruuLuulluRdrUruulDDDDulllddlddrrruURlddrruLuuullllluRRRRdrUruulDDDDDDuuulllddlddrrrRuulDuUruLLLulDD"},
  {id:96,world:10,worldName:"Grandmaster",boxes:6,pushes:40,moves:99,
   rows:["#####-#####","# . #-#   #","#  ####$  #","#      $@ #","#   $$ #.##","#  $ .*.. #","#######   #","------##  #","------## ##","------#   #","------#####"],
   solution:"LLLLLdlUrrrrrruulDrdLLLLLdlluRRRRRRurDDDrddlUruLuullllldldRRUluRRRRurDDulldLullddrUluRRRRurDllllllU"},
  {id:97,world:10,worldName:"Grandmaster",boxes:6,pushes:42,moves:162,
   rows:["#######-----","#     #-----","#   . #-----","#  .###-----","#  #########","#     $.$  #","#  ## $ *. #","#  ### $ # #","#+$        #","############"],
   solution:"RRRRRRRuLuuRDrrddLLLLLLLLuuurrrdRRRlddrUdllUdrrrruuuLrdddlluluuLLrrddlUluLLrrdrruLdddrrrruuulLrrdddllululuLLrdrddlllluuUUddddrrrruuullLrrdrddlllluuUluuRlddrUUluRR"},
  {id:98,world:10,worldName:"Grandmaster",boxes:6,pushes:43,moves:113,
   rows:["##########-","#.     $ ##","#  $$$    #","#    $ #$ #","# .# ###@##","#. #  ####-","#..    #---","#  ##  #---","#.######---","###--------"],
   solution:"UruLuLLddLLdddlluuuuurrDDDDrdLLLulDDurrruuuLruulldDDDuurruLLulDDDDuurrrrruLLLLulDDDuurrrrrurrdLLLLLulDDurrrruLLLL"},
  {id:99,world:10,worldName:"Grandmaster",boxes:6,pushes:44,moves:254,
   rows:["---#########","---#    .  #","---#       #","---#.# . . #","---###  #  #","-----## #. #","####### .  #","#@$   $  $ #","###   #  $ #","--#####$$# #","------#    #","------######"],
   solution:"RRdrruRRdrUluuuurrdddrddddllUUddrruuLrddlllUdrrruulUUruuulllddddRluuuurrdrddddddlluUrruulLrrddllUlUUUdddrdrruulLdllldlluRRRRUrrrddlldlUrrruulUruuullllddrUrrrdddlllUUddrrrddlUdlUdlUrrruulUdrddlUdllUUddrruruuuulldLUrrrdddddllluuUlUdrdddrruruuuulllLLulDurrR"},
  {id:100,world:10,worldName:"Grandmaster",boxes:5,pushes:56,moves:206,
   rows:["####-------","#  #####---","#  $ $ #---","#    $@#---","##.$  ##---","-#$## #####","##  . .   #","# ##  ##  #","#.       .#","###########"],
   solution:"LdddlllUURlddrrruuuLrdddllluurRurDDDDldRRRRuullluulllUluurDDDrruuLrddlluRurDldRurDDDDurrrddllLLLLrruuruuulllluurDldRRurDldRurDDDlllUUruulldRRurDldRurDDulllddrrddrrrruullLLddrUluRuulllddRluuurrrruLLLdlluurDD"}
  ];
});
